# Generated by Django 5.0.4 on 2024-05-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '(1) Trash'), (2, '(2) Horrible'), (3, '(3) Very Bad'), (4, '(4) Bad'), (5, '(5) Avarage'), (6, '(6) Fine'), (7, '(7) Good'), (8, '(8) Very Good'), (9, '(9) Great'), (10, '(10) Masterpiece')]),
        ),
    ]
